# Generated by Django 3.2 on 2021-04-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poject',
            new_name='Project',
        ),
    ]
